// Package provenance holds the source-set catalogs — the original KeyForge cards
// that vactrol cards are derived from — and the types used to tag a card with its
// origin for coverage tracking. The catalogs are embedded JSON generated by
// `mage generateProvenance` (magefiles/genprovenance); vactrol diverges from these
// originals, so a card's
// provenance is an explicit, stable pointer (set + collector number) rather than
// anything derived from its current name.
package provenance

import (
	"embed"
	"encoding/json"
	"sort"
	"strconv"
	"sync"
)

//go:embed *.json
var catalogFS embed.FS

// SourceSet identifies an original card set. Slug matches the embedded catalog
// file name; Code and Name are for display.
type SourceSet struct {
	Slug string
	Code string
	Name string
}

// Ref points at a single original card: its source set and collector number.
type Ref struct {
	Set    SourceSet
	Number int
}

// Card is one original card as recorded in a source catalog.
type Card struct {
	Number int
	Name   string
	House  string
	Type   string
	Rarity string
	Text   string
}

// Set is a source set together with all of its cards.
type Set struct {
	SourceSet
	Cards []Card
}

// The known source sets, in release order. Slugs match the catalog file names.
var (
	CallOfTheArchons  = SourceSet{"callofthearchons", "CotA", "Call of the Archons"}
	AgeOfAscension    = SourceSet{"ageofascension", "AoA", "Age of Ascension"}
	WorldsCollide     = SourceSet{"worldscollide", "WC", "Worlds Collide"}
	MassMutation      = SourceSet{"massmutation", "MM", "Mass Mutation"}
	DarkTidings       = SourceSet{"darktidings", "DT", "Dark Tidings"}
	WindsOfExchange   = SourceSet{"windsofexchange", "WoE", "Winds of Exchange"}
	GrimReminders     = SourceSet{"grimreminders", "GR", "Grim Reminders"}
	AemberSkies       = SourceSet{"aemberskies", "AS", "Æmber Skies"}
	TokensOfChange    = SourceSet{"tokensofchange", "ToC", "Tokens of Change"}
	MoreMutation      = SourceSet{"moremutation", "MoM", "More Mutation"}
	Menagerie         = SourceSet{"menagerie", "Men", "Menagerie"}
	VaultMasters2025  = SourceSet{"vaultmasters2025", "VM25", "Vault Masters 2025"}
	PropheticVisions  = SourceSet{"propheticvisions", "PV", "Prophetic Visions"}
	CrucibleClash     = SourceSet{"crucibleclash", "CC", "Crucible Clash"}
	DraconianMeasures = SourceSet{"draconianmeasures", "DM", "Draconian Measures"}
)

// order lists every known set; Sets() skips any without an embedded catalog.
var order = []SourceSet{
	CallOfTheArchons, AgeOfAscension, WorldsCollide, MassMutation, DarkTidings,
	WindsOfExchange, GrimReminders, AemberSkies, TokensOfChange, MoreMutation,
	Menagerie, VaultMasters2025, PropheticVisions, CrucibleClash, DraconianMeasures,
}

var (
	loadOnce sync.Once
	sets     []Set
)

func load() {
	for _, ss := range order {
		data, err := catalogFS.ReadFile(ss.Slug + ".json")
		if err != nil {
			continue // a set without a catalog is simply skipped
		}
		var raw []struct {
			Number string `json:"number"`
			Name   string `json:"name"`
			House  string `json:"house"`
			Type   string `json:"type"`
			Rarity string `json:"rarity"`
			Text   string `json:"text"`
		}
		if err := json.Unmarshal(data, &raw); err != nil {
			continue
		}
		cards := make([]Card, 0, len(raw))
		for _, r := range raw {
			n, _ := strconv.Atoi(r.Number)
			cards = append(cards, Card{
				Number: n, Name: r.Name, House: r.House,
				Type: r.Type, Rarity: r.Rarity, Text: r.Text,
			})
		}
		sort.Slice(cards, func(i, j int) bool { return cards[i].Number < cards[j].Number })
		sets = append(sets, Set{SourceSet: ss, Cards: cards})
	}
}

// Sets returns every source set that has an embedded catalog, in release order.
func Sets() []Set {
	loadOnce.Do(load)
	return sets
}
