// Package provenance holds the source-set catalogs — the original KeyForge cards
// that vex cards are derived from — and the types used to tag a card with its
// origin for coverage tracking. The catalogs are embedded JSON generated by
// `mage tool:importProvenance` (magefiles/cardlookup); vex diverges from these
// originals, so a card's
// provenance is an explicit, stable pointer (set + collector number) rather than
// anything derived from its current name.
//
// A collector number is a string, not an int: most cards number 001–364, but a
// set's reference cards carry lettered numbers — anomalies S01+, Worlds Collide's
// A01+, prophecies P01+ — so the number cannot be an integer without losing them.
//
// Provenance is bookkeeping only. It exists so the author can track which original
// KeyForge card each implementation is based on and confirm that every original is
// eventually covered. It is never consulted by the engine or by deck generation,
// and no card behavior, deck-generation rule, or set membership depends on it.
package provenance

import (
	"embed"
	"encoding/json/v2"
	"sort"
	"sync"
)

//go:embed *.json
var catalogFS embed.FS

// SourceSet identifies an original card set. Slug matches the embedded catalog
// file name; Code and Name are for display.
type SourceSet struct {
	Slug string
	Code string
	Name string
}

// Ref points at a single original card: its source set and collector number.
type Ref struct {
	Set    SourceSet
	Number string
}

// Card is one original card as recorded in a source catalog.
type Card struct {
	Number   string
	Name     string
	House    string
	Type     string
	Rarity   string
	Text     string
	Traits   []string
	Keywords []string
	Power    int
	Armor    int
	Amber    int
}

// Set is a source set together with all of its cards.
type Set struct {
	SourceSet
	Cards []Card
}

// The known source sets, in release order. Slugs match the catalog file names.
var (
	CallOfTheArchons  = SourceSet{"callofthearchons", "CotA", "Call of the Archons"}
	AgeOfAscension    = SourceSet{"ageofascension", "AoA", "Age of Ascension"}
	WorldsCollide     = SourceSet{"worldscollide", "WC", "Worlds Collide"}
	AnomalyExpansion  = SourceSet{"anomalyexpansion", "AE", "Anomaly Expansion"}
	MassMutation      = SourceSet{"massmutation", "MM", "Mass Mutation"}
	DarkTidings       = SourceSet{"darktidings", "DT", "Dark Tidings"}
	WindsOfExchange   = SourceSet{"windsofexchange", "WoE", "Winds of Exchange"}
	Unchained2022     = SourceSet{"unchained2022", "UC22", "Unchained 2022"}
	VaultMasters2023  = SourceSet{"vaultmasters2023", "VM23", "Vault Masters 2023"}
	GrimReminders     = SourceSet{"grimreminders", "GR", "Grim Reminders"}
	Menagerie         = SourceSet{"menagerie", "Men", "Menagerie"}
	VaultMasters2024  = SourceSet{"vaultmasters2024", "VM24", "Vault Masters 2024"}
	AemberSkies       = SourceSet{"aemberskies", "AS", "Æmber Skies"}
	TokensOfChange    = SourceSet{"tokensofchange", "ToC", "Tokens of Change"}
	MoreMutation      = SourceSet{"moremutation", "MoMu", "More Mutation"}
	PropheticVisions  = SourceSet{"propheticvisions", "PV", "Prophetic Visions"}
	MartianCivilWar   = SourceSet{"martiancivilwar", "MCW", "Martian Civil War"}
	Discovery         = SourceSet{"discovery", "D", "Discovery"}
	CrucibleClash     = SourceSet{"crucibleclash", "CC", "Crucible Clash"}
	DraconianMeasures = SourceSet{"draconianmeasures", "DM", "Draconian Measures"}
	VaultMasters2025  = SourceSet{"vaultmasters2025", "VM25", "Vault Masters 2025"}
	VaultMasters2026  = SourceSet{"vaultmasters2026", "VM26", "Vault Masters 2026"}
)

// order lists every known set; Sets() skips any without an embedded catalog.
var order = []SourceSet{
	CallOfTheArchons,
	AgeOfAscension,
	WorldsCollide,
	AnomalyExpansion,
	MassMutation,
	DarkTidings,
	WindsOfExchange,
	Unchained2022,
	VaultMasters2023,
	GrimReminders,
	Menagerie,
	VaultMasters2024,
	AemberSkies,
	TokensOfChange,
	MoreMutation,
	PropheticVisions,
	MartianCivilWar,
	Discovery,
	CrucibleClash,
	DraconianMeasures,
	VaultMasters2025,
	VaultMasters2026,
}

var (
	loadOnce sync.Once
	sets     []Set
)

func load() {
	for _, ss := range order {
		data, err := catalogFS.ReadFile(ss.Slug + ".json")
		if err != nil {
			continue // a set without a catalog is simply skipped
		}
		var raw []struct {
			Number   string   `json:"number"`
			Name     string   `json:"name"`
			House    string   `json:"house"`
			Type     string   `json:"type"`
			Rarity   string   `json:"rarity"`
			Text     string   `json:"text"`
			Traits   []string `json:"traits"`
			Keywords []string `json:"keywords"`
			Power    int      `json:"power"`
			Armor    int      `json:"armor"`
			Amber    int      `json:"amber"`
		}
		if err := json.Unmarshal(data, &raw); err != nil {
			continue
		}
		cards := make([]Card, 0, len(raw))
		for _, r := range raw {
			cards = append(cards, Card{
				Number: r.Number, Name: r.Name, House: r.House,
				Type: r.Type, Rarity: r.Rarity, Text: r.Text,
				Traits: r.Traits, Keywords: r.Keywords,
				Power: r.Power, Armor: r.Armor, Amber: r.Amber,
			})
		}
		sort.Slice(cards, func(i, j int) bool { return cards[i].Number < cards[j].Number })
		sets = append(sets, Set{
			SourceSet: ss,
			Cards:     cards,
		})
	}
}

// Sets returns every source set that has an embedded catalog, in release order.
func Sets() []Set {
	loadOnce.Do(load)
	return sets
}
