// Command genrules assembles the Vactrol rulebook (docs/rulebook.md) from the
// engine's typed term registry. It is the source of `mage generateRules` (and
// half of `mage gen`).
//
// The rules text lives next to the code that enforces it as engine.RuleTerms()
// (ADR 0018): each keyword, card type, trigger, and rule-bearing effect registers
// a RuleTerm carrying its section, title, and body. genrules renders that table —
// grouping terms by section and sorting alphabetically by title — instead of
// re-parsing Go source, so a new term flows through as data. Terms may share a
// title to gather several code sites under one heading, and carry a subtitle to
// nest beneath it.
//
// Foundational prose that isn't tied to any one term — the overview and each
// section's intro — also lives in the engine registry (engine.RuleOverview() and
// engine.RuleSectionIntro()) and is spliced in around the rendered entries, so the
// whole rulebook flows through one typed contract.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"

	"github.com/dmikalova/vactrol/internal/engine"
)

const (
	// outputFile is the assembled rulebook.
	outputFile = "docs/rulebook.md"
)

// section is one top-level rulebook section. Sections print in this fixed order;
// the entries within each are sorted alphabetically by title, so the order of
// terms is data-driven and never has to be maintained by hand.
type section struct {
	key   string // directive key that files entries here, e.g. "keyword"
	title string // heading printed for the section, e.g. "Keywords"
}

// sections is the ordered spine of the rulebook. Add a section by adding a row
// here (and, optionally, an engine.RuleSectionIntro for it).
var sections = []section{
	{"turn", "The Turn"},
	{"combat", "Combat"},
	{"cardtype", "Card Types"},
	{"keyword", "Keywords"},
	{"ability", "Abilities"},
	{"effect", "Effects"},
}

// entry is one harvested rulebook term: its title, an optional subheading that
// groups several entries under one title, and its body Markdown.
type entry struct {
	title    string
	subtitle string
	body     string
}

func main() {
	check := flag.Bool("check", false,
		"verify the committed rulebook is up to date; do not write (ADR 0018)")
	flag.Parse()

	byKey := map[string][]entry{}
	for _, t := range engine.RuleTerms() {
		byKey[string(t.Section)] = append(byKey[string(t.Section)], entry{
			title:    t.Title,
			subtitle: t.Subtitle,
			body:     t.Body,
		})
	}

	doc := render(byKey)

	if *check {
		// Freshness gate: render into memory and compare to the committed file,
		// so a rulebook left stale by a forgotten `mage gen` fails the build
		// without touching the working tree.
		existing, err := os.ReadFile(outputFile)
		if err != nil {
			fmt.Fprintln(os.Stderr, "genrules:", err)
			os.Exit(1)
		}
		if string(existing) != doc {
			fmt.Fprintf(os.Stderr,
				"genrules: %s is stale; run `mage gen`\n", outputFile)
			os.Exit(1)
		}
		fmt.Printf("genrules: %s is up to date\n", outputFile)
		return
	}

	if err := os.WriteFile(outputFile, []byte(doc), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "genrules:", err)
		os.Exit(1)
	}

	var n int
	for _, es := range byKey {
		n += len(es)
	}
	fmt.Printf("genrules: wrote %s (%d entries)\n", outputFile, n)
}

// render assembles the full rulebook Markdown from the registered terms and the
// registered framing prose.
func render(byKey map[string][]entry) string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by magefiles/genrules; DO NOT EDIT. -->\n")
	b.WriteString(
		"<!-- Terms and prose come from engine.RuleTerms()/RuleOverview()/RuleSectionIntro() (ADR 0018); -->\n",
	)
	b.WriteString("<!-- run `mage gen` to regenerate. -->\n\n")

	overview := engine.RuleOverview()
	if overview != "" {
		b.WriteString(overview)
		b.WriteString("\n\n")
	}

	var index []indexEntry
	for _, sec := range sections {
		entries := byKey[sec.key]
		intro := engine.RuleSectionIntro(engine.Section(sec.key))
		if len(entries) == 0 && intro == "" {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n", sec.title)
		if intro != "" {
			b.WriteString(intro)
			b.WriteString("\n\n")
		}
		for _, gr := range sectionLead(groupByTitle(entries), sec.title) {
			// An entry whose title matches its section (e.g. Combat) would render a
			// heading identical to the section's, so emit its body directly under
			// the section instead of repeating the heading.
			if !strings.EqualFold(gr.title, sec.title) {
				fmt.Fprintf(&b, "### %s\n\n", gr.title)
			}
			index = append(index, indexEntry{gr.title, anchor(gr.title)})
			// Untitled parts render first as the heading's own body; subheaded
			// parts follow, ordered by subheading (number them to control order).
			var subbed []entry
			for _, p := range gr.parts {
				if p.subtitle == "" {
					writeBody(&b, p.body)
					continue
				}
				subbed = append(subbed, p)
			}
			sort.SliceStable(subbed, func(i, j int) bool {
				return strings.ToLower(subbed[i].subtitle) < strings.ToLower(subbed[j].subtitle)
			})
			for _, p := range subbed {
				fmt.Fprintf(&b, "#### %s\n\n", p.subtitle)
				index = append(index, indexEntry{p.subtitle, anchor(p.subtitle)})
				writeBody(&b, p.body)
			}
		}
	}

	writeIndex(&b, index)

	return strings.TrimRight(b.String(), "\n") + "\n"
}

// indexEntry is one term in the trailing alphabetical index: the heading text and
// the GitHub-style anchor slug that links to it.
type indexEntry struct {
	title  string
	anchor string
}

// writeIndex appends the alphabetical index of every term heading, each linking
// back to its section. It is emitted once, after all sections.
func writeIndex(b *strings.Builder, index []indexEntry) {
	if len(index) == 0 {
		return
	}
	sort.SliceStable(index, func(i, j int) bool {
		return strings.ToLower(index[i].title) < strings.ToLower(index[j].title)
	})
	b.WriteString("## Index\n\n")
	for _, e := range index {
		fmt.Fprintf(b, "- [%s](#%s)\n", e.title, e.anchor)
	}
	b.WriteString("\n")
}

// anchor renders a term title as a GitHub-style heading slug: lowercased, with
// spaces and hyphens collapsed to hyphens and every other character dropped.
// Letters outside ASCII are kept — GitHub slugs "Æmber" as "æmber".
func anchor(title string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(title) {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			b.WriteRune(r)
		case r == ' ' || r == '-':
			b.WriteByte('-')
		}
	}
	return b.String()
}

// titleGroup gathers every entry sharing a title so several code sites can feed
// one rulebook heading.
type titleGroup struct {
	title string
	parts []entry
}

// groupByTitle merges entries that share a title and returns the groups sorted
// alphabetically by title, each keeping its parts in harvest order.
func groupByTitle(entries []entry) []titleGroup {
	var groups []titleGroup
	index := map[string]int{}
	for _, e := range entries {
		i, ok := index[e.title]
		if !ok {
			i = len(groups)
			index[e.title] = i
			groups = append(groups, titleGroup{title: e.title})
		}
		groups[i].parts = append(groups[i].parts, e)
	}
	sort.SliceStable(groups, func(i, j int) bool {
		return strings.ToLower(groups[i].title) < strings.ToLower(groups[j].title)
	})
	return groups
}

// sectionLead reorders groups so the entry whose title equals the section (its
// overview, rendered without a repeated heading) leads, ahead of the ### terms.
func sectionLead(groups []titleGroup, section string) []titleGroup {
	sort.SliceStable(groups, func(i, j int) bool {
		return strings.EqualFold(groups[i].title, section) &&
			!strings.EqualFold(groups[j].title, section)
	})
	return groups
}

// writeBody appends a non-empty body paragraph followed by a blank line.
func writeBody(b *strings.Builder, body string) {
	if body != "" {
		b.WriteString(body)
		b.WriteString("\n\n")
	}
}
