// Code generated by "mage tool:stub callofthearchons"; DO NOT EDIT.

package callofthearchons

import "github.com/dmikalova/vactrol/internal/card"

// set is Call of the Archons's registrar: every card in this package declares its
// home set by registering through set.New, so deck generation groups the card
// by this set alone and never infers it from provenance (ADR 0003).
var set = card.NewSet(card.CotA)
